package org.phellang.tools.generator

import org.phellang.tools.model.PhpFunctionDoc
import org.phellang.tools.transformer.StringEscaper
import java.io.File

/**
 * Emits `registry/PhpNativeFunctions.kt` from the parsed [PhpFunctionDoc]s.
 *
 * Functions are grouped into one private list per extension (keeping each generated method well under
 * the JVM's 64 KB bytecode limit), and `phpNativeFunctions()` concatenates them. The file sits at the
 * registry root, not `registry/data/`, so the api.json generator (`updatePhelRegistry`) never touches
 * it, and the `PHP_NATIVE` wiring in Namespace.kt / PhelFunctionRegistry.kt stays hand-maintained.
 */
class PhpRegistryGenerator(private val registryDirectory: File) {

    fun generate(functions: List<PhpFunctionDoc>, ref: String) {
        val byExtension = functions.sortedBy { it.name }.groupBy { it.extension }.toSortedMap()

        val out = StringBuilder()
        out.appendLine("package org.phellang.registry")
        out.appendLine()
        appendHeader(out, functions.size, byExtension.keys, ref)
        appendHelpers(out)

        val extensionFunctions = mutableListOf<String>()
        for ((extension, extensionDocs) in byExtension) {
            val functionName = "php${extension.replaceFirstChar(Char::uppercase)}Functions"
            extensionFunctions += functionName
            out.appendLine("private fun $functionName(): List<PhelFunction> = listOf(")
            for (doc in extensionDocs) {
                val name = StringEscaper.toKotlinString("php/${doc.name}")
                val signature = StringEscaper.toKotlinString(doc.signature)
                val summary = StringEscaper.toKotlinString(StringEscaper.escapeHtml(doc.summary))
                out.appendLine("    php($name, $signature, $summary),")
            }
            out.appendLine(")")
            out.appendLine()
        }

        out.appendLine("/** Native PHP library functions surfaced through the php/ prefix (generated; see updatePhpRegistry). */")
        out.appendLine("internal fun phpNativeFunctions(): List<PhelFunction> =")
        out.appendLine("    " + extensionFunctions.joinToString(" +\n    ") { "$it()" })

        File(registryDirectory, "PhpNativeFunctions.kt").writeText(out.toString())
        println("Wrote PhpNativeFunctions.kt (${functions.size} functions, ${byExtension.size} extensions)")
    }

    private fun appendHeader(out: StringBuilder, count: Int, extensions: Set<String>, ref: String) {
        out.appendLine("// GENERATED by updatePhpRegistry — do not edit by hand. Regenerate with:")
        out.appendLine("//   ./gradlew updatePhpRegistry")
        out.appendLine("//")
        out.appendLine("// $count native PHP functions from these php/doc-en extensions:")
        out.appendLine("//   ${extensions.joinToString(", ")}")
        out.appendLine("//")
        out.appendLine("// Summaries (<refpurpose>) and signatures (<methodsynopsis>) are derived from the PHP")
        out.appendLine("// Documentation (https://github.com/php/doc-en), pinned at commit")
        out.appendLine("//   $ref")
        out.appendLine("// and licensed under CC-BY 3.0 (https://creativecommons.org/licenses/by/3.0/legalcode).")
        out.appendLine("// Each entry links to its rendered php.net page.")
        out.appendLine()
    }

    private fun appendHelpers(out: StringBuilder) {
        out.appendLine("/** The php.net manual URL for a bare PHP function name (array_map -> function.array-map.php). */")
        out.appendLine("private fun phpDoc(function: String): String =")
        out.appendLine("    \"https://www.php.net/manual/en/function.\${function.replace('_', '-')}.php\"")
        out.appendLine()
        out.appendLine("private fun php(name: String, signature: String, summary: String): PhelFunction = PhelFunction(")
        out.appendLine("    namespace = \"php\",")
        out.appendLine("    name = name,")
        out.appendLine("    signature = signature,")
        out.appendLine("    completion = CompletionInfo(tailText = summary, priority = PhelCompletionPriority.PHP_INTEROP),")
        out.appendLine("    documentation = DocumentationInfo(")
        out.appendLine("        summary = summary,")
        out.appendLine("        links = DocumentationLinks(docs = phpDoc(name.removePrefix(\"php/\"))),")
        out.appendLine("    ),")
        out.appendLine(")")
        out.appendLine()
    }
}
