package org.phellang.unit.language.psi

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test
import org.phellang.language.psi.PhelProjectNamespaceFinder
import org.phellang.registry.Namespace

class PhelProjectNamespaceFinderTest {

    @Nested
    inner class ExtractShortNamespace {

        @Test
        fun `extracts short name from full namespace`() {
            assertEquals("utils", PhelProjectNamespaceFinder.extractShortNamespace("phel-project\\utils"))
            assertEquals("math", PhelProjectNamespaceFinder.extractShortNamespace("phel-project\\math"))
            assertEquals("core", PhelProjectNamespaceFinder.extractShortNamespace("phel.core"))
        }

        @Test
        fun `handles nested namespaces`() {
            assertEquals("helpers", PhelProjectNamespaceFinder.extractShortNamespace("my-app\\lib\\helpers"))
            assertEquals("deep", PhelProjectNamespaceFinder.extractShortNamespace("a\\b\\c\\deep"))
        }

        @Test
        fun `returns same string if no separator`() {
            assertEquals("utils", PhelProjectNamespaceFinder.extractShortNamespace("utils"))
            assertEquals("core", PhelProjectNamespaceFinder.extractShortNamespace("core"))
        }

        @Test
        fun `handles empty string`() {
            assertEquals("", PhelProjectNamespaceFinder.extractShortNamespace(""))
        }
    }

    @Nested
    inner class IsStandardLibrary {

        @Test
        fun `recognizes standard library namespaces`() {
            assertTrue(PhelProjectNamespaceFinder.isStandardLibrary("phel.string"))
            assertTrue(PhelProjectNamespaceFinder.isStandardLibrary("phel.json"))
            assertTrue(PhelProjectNamespaceFinder.isStandardLibrary("phel.core"))
            assertTrue(PhelProjectNamespaceFinder.isStandardLibrary("phel.http"))
            assertTrue(PhelProjectNamespaceFinder.isStandardLibrary("phel.html"))
        }

        @Test
        fun `rejects non-standard namespaces`() {
            assertFalse(PhelProjectNamespaceFinder.isStandardLibrary("phel-project\\utils"))
            assertFalse(PhelProjectNamespaceFinder.isStandardLibrary("my-app\\core"))
            assertFalse(PhelProjectNamespaceFinder.isStandardLibrary("string"))
        }
    }

    @Nested
    inner class StandardLibraryNamespaces {

        @Test
        fun `all expected standard library namespaces are defined`() {
            val expected = setOf(
                "phel.ai",
                "phel.async",
                "phel.base64",
                "phel.cli",
                "phel.core",
                "phel.debug",
                "phel.edn",
                "phel.html",
                "phel.http",
                "phel.http-client",
                "phel.http_client",
                "phel.json",
                "phel.match",
                "phel.mock",
                "phel.pprint",
                "phel.reader",
                "phel.reflect",
                "phel.repl",
                "phel.router",
                "phel.schema",
                "phel.schema.coercer",
                "phel.schema.explainer",
                "phel.schema.generator",
                "phel.schema.instrument",
                "phel.schema.registry",
                "phel.schema.validator",
                "phel.string",
                "phel.test",
                "phel.test.gen",
                "phel.test.rose",
                "phel.test.selector",
                "phel.test.shrink",
                "phel.trace",
                "phel.transit",
                "phel.walk",
                "phel.watch",
            )
            assertEquals(expected, PhelProjectNamespaceFinder.STANDARD_LIBRARY_NAMESPACES)
        }

        /**
         * This map is hand-maintained while [Namespace] is regenerated by `updatePhelRegistry`, so
         * a namespace added to `NamespaceConfig` silently misses it. That drift is not cosmetic:
         * an absent entry makes `(:require phel\<ns>)` report an unknown namespace. `phel.trace`
         * shipped in Phel v0.49.0 and was missing here until this guard was added.
         *
         * `PHP_INTEROP` and `PHP_NATIVE` are excluded: they surface PHP functions through the
         * `php/` prefix and are never required as a Phel namespace.
         */
        @Test
        fun `every registry namespace is a known standard library namespace`() {
            val requireable = Namespace.entries - Namespace.PHP_INTEROP - Namespace.PHP_NATIVE

            val missing = requireable.filter { ns ->
                // SCHEMA_COERCER -> schema.coercer, HTTP_CLIENT -> http-client or http_client
                val stem = ns.name.lowercase()
                val candidates = setOf(stem, stem.replace('_', '.'), stem.replace('_', '-'))
                candidates.none { "phel.$it" in PhelProjectNamespaceFinder.STANDARD_LIBRARY_NAMESPACES }
            }

            assertTrue(
                missing.isEmpty(),
                "Namespaces known to the registry but missing from PhelProjectNamespaceFinder: $missing",
            )
        }

        @Test
        fun `short to full mapping contains all namespaces`() {
            val shortToFull = PhelProjectNamespaceFinder.STANDARD_LIBRARY_SHORT_TO_FULL

            assertEquals("phel.string", shortToFull["string"])
            assertEquals("phel.json", shortToFull["json"])
            assertEquals("phel.core", shortToFull["core"])
        }

        @Test
        fun `getStandardLibraryFullNamespace returns correct namespace`() {
            assertEquals("phel.string", PhelProjectNamespaceFinder.getStandardLibraryFullNamespace("string"))
            assertEquals("phel.json", PhelProjectNamespaceFinder.getStandardLibraryFullNamespace("json"))
            assertEquals("phel.core", PhelProjectNamespaceFinder.getStandardLibraryFullNamespace("core"))
        }

        @Test
        fun `getStandardLibraryFullNamespace is case insensitive`() {
            assertEquals("phel.string", PhelProjectNamespaceFinder.getStandardLibraryFullNamespace("STRING"))
            assertEquals("phel.json", PhelProjectNamespaceFinder.getStandardLibraryFullNamespace("JSON"))
        }

        @Test
        fun `getStandardLibraryFullNamespace returns null for unknown`() {
            assertNull(PhelProjectNamespaceFinder.getStandardLibraryFullNamespace("unknown"))
            assertNull(PhelProjectNamespaceFinder.getStandardLibraryFullNamespace("php"))
        }
    }
}
